/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pf;

/**
 *
 * @author Vanessa
 */
public class VEmpleado extends javax.swing.JFrame {
    //private Empleado empleado;

    /**
     * Creates new form VUsuario
     */
    public VEmpleado() {
        super("Biblioteca/Empleado");
        //empleado = emp;
        initComponents();
        String nombre = "Bienvenido  " + "Vanessa"; //+ empleado.getNombre();
        NomUsuario.setText(nombre);
        grupoOpciones.add(opcID1);
        grupoOpciones.add(opcTitulo1);
        grupoOpciones.add(opcAutor);
        grupoOpciones.add(opcEditorial);
        grupoOpciones2.add(opcID2);
        grupoOpciones2.add(opcTitulo2);
        grupoOpciones3.add(opcID3);
        grupoOpciones3.add(opcNombre3);
        grupoOpciones4.add(opcID4);
        grupoOpciones4.add(opcNombre4);
        grupoOpciones5.add(opcID5);
        grupoOpciones5.add(opcNombre5);
        grupoOpciones5.add(opcFecha5);
        grupoOpciones6.add(opcID6);
        grupoOpciones6.add(opcNombre6);
        grupoOpciones6.add(opcFecha6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOpciones = new javax.swing.ButtonGroup();
        grupoOpciones2 = new javax.swing.ButtonGroup();
        grupoOpciones3 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        grupoOpciones4 = new javax.swing.ButtonGroup();
        grupoOpciones5 = new javax.swing.ButtonGroup();
        grupoOpciones6 = new javax.swing.ButtonGroup();
        BuscarLibro = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        TBuscarL = new javax.swing.JTextField();
        opcTitulo1 = new javax.swing.JRadioButton();
        opcID1 = new javax.swing.JRadioButton();
        opcAutor = new javax.swing.JRadioButton();
        opcEditorial = new javax.swing.JRadioButton();
        NomUsuario = new javax.swing.JLabel();
        BVerLibros = new javax.swing.JButton();
        BDatos = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TBorrarL = new javax.swing.JTextField();
        opcTitulo2 = new javax.swing.JRadioButton();
        opcID2 = new javax.swing.JRadioButton();
        BuscarLibro1 = new java.awt.Button();
        BAgregarL = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BorrarUE = new java.awt.Button();
        BVerUsuarios = new javax.swing.JButton();
        BuscarUE = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        opcNombre3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        opcID3 = new javax.swing.JRadioButton();
        TBorrarUE = new javax.swing.JTextField();
        opcNombre4 = new javax.swing.JRadioButton();
        opcID4 = new javax.swing.JRadioButton();
        TBuscarUE = new javax.swing.JTextField();
        BoxBuscarUE = new javax.swing.JComboBox<>();
        BoxBorrarUE = new javax.swing.JComboBox<>();
        BVerEmpleados = new javax.swing.JButton();
        BoxBuscarUE1 = new javax.swing.JComboBox<>();
        BoxBorrarUE1 = new javax.swing.JComboBox<>();
        BVerMultas = new javax.swing.JButton();
        BorraPM = new java.awt.Button();
        BVerPrestamos = new javax.swing.JButton();
        BuscarLibro5 = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        opcNombre5 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        opcID5 = new javax.swing.JRadioButton();
        TBorrarPM = new javax.swing.JTextField();
        opcNombre6 = new javax.swing.JRadioButton();
        opcID6 = new javax.swing.JRadioButton();
        TBuscarPM = new javax.swing.JTextField();
        BAgregarPM = new javax.swing.JButton();
        opcFecha5 = new javax.swing.JRadioButton();
        opcFecha6 = new javax.swing.JRadioButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BuscarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BuscarLibro.setLabel("Buscar");
        BuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarLibroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jLabel2.setText("Borrar");

        opcTitulo1.setText("Titulo");
        opcTitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcTitulo1ActionPerformed(evt);
            }
        });

        opcID1.setText("ID");
        opcID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcID1ActionPerformed(evt);
            }
        });

        opcAutor.setText("Autor");
        opcAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAutorActionPerformed(evt);
            }
        });

        opcEditorial.setText("Editorial");
        opcEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcEditorialActionPerformed(evt);
            }
        });

        NomUsuario.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        NomUsuario.setText("jLabel4");

        BVerLibros.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        BVerLibros.setText("Ver todos");
        BVerLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerLibrosActionPerformed(evt);
            }
        });

        BDatos.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        BDatos.setText("Mis datos");
        BDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDatosActionPerformed(evt);
            }
        });

        BSalir.setText("Cerrar Sesión");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jLabel3.setText("Buscar");

        opcTitulo2.setText("Titulo");
        opcTitulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcTitulo2ActionPerformed(evt);
            }
        });

        opcID2.setText("ID");
        opcID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcID2ActionPerformed(evt);
            }
        });

        BuscarLibro1.setActionCommand("Borrar");
        BuscarLibro1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BuscarLibro1.setLabel("Borrar");
        BuscarLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarLibro1ActionPerformed(evt);
            }
        });

        BAgregarL.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        BAgregarL.setText("Agregar");
        BAgregarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarLActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel4.setText("Libros");

        BorrarUE.setActionCommand("Borrar");
        BorrarUE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BorrarUE.setLabel("Borrar");
        BorrarUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarUEActionPerformed(evt);
            }
        });

        BVerUsuarios.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        BVerUsuarios.setText("Ver todos los usuarios");
        BVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerUsuariosActionPerformed(evt);
            }
        });

        BuscarUE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BuscarUE.setLabel("Buscar");
        BuscarUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarUEActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jLabel5.setText("Borrar");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel6.setText("Usuarios y empleados");

        opcNombre3.setText("Nombre");
        opcNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcNombre3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jLabel7.setText("Buscar");

        opcID3.setText("ID");
        opcID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcID3ActionPerformed(evt);
            }
        });

        opcNombre4.setText("Nombre");
        opcNombre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcNombre4ActionPerformed(evt);
            }
        });

        opcID4.setText("ID");
        opcID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcID4ActionPerformed(evt);
            }
        });

        BoxBuscarUE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Usuario", "Empleado" }));

        BoxBorrarUE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Usuario", "Empleado" }));

        BVerEmpleados.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        BVerEmpleados.setText("Ver todos los empleados");
        BVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerEmpleadosActionPerformed(evt);
            }
        });

        BoxBuscarUE1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Préstamos", "Multas" }));

        BoxBorrarUE1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Préstamos", "Multas" }));

        BVerMultas.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        BVerMultas.setText("Ver todos las multas");
        BVerMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerMultasActionPerformed(evt);
            }
        });

        BorraPM.setActionCommand("Borrar");
        BorraPM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BorraPM.setLabel("Borrar");
        BorraPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorraPMActionPerformed(evt);
            }
        });

        BVerPrestamos.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        BVerPrestamos.setText("Ver todos los préstamos");
        BVerPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerPrestamosActionPerformed(evt);
            }
        });

        BuscarLibro5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BuscarLibro5.setLabel("Buscar");
        BuscarLibro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarLibro5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jLabel8.setText("Borrar");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel9.setText("Préstamos y multas");

        opcNombre5.setText("Nombre");
        opcNombre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcNombre5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jLabel10.setText("Buscar");

        opcID5.setText("ID");
        opcID5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcID5ActionPerformed(evt);
            }
        });

        opcNombre6.setText("Nombre");
        opcNombre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcNombre6ActionPerformed(evt);
            }
        });

        opcID6.setText("ID");
        opcID6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcID6ActionPerformed(evt);
            }
        });

        BAgregarPM.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        BAgregarPM.setText("Agregar");
        BAgregarPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarPMActionPerformed(evt);
            }
        });

        opcFecha5.setText("Fecha");
        opcFecha5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcFecha5ActionPerformed(evt);
            }
        });

        opcFecha6.setText("Fecha");
        opcFecha6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcFecha6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(TBuscarL, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(opcID1)
                            .addGap(18, 18, 18)
                            .addComponent(opcTitulo1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opcAutor)
                            .addGap(18, 18, 18)
                            .addComponent(opcEditorial))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(opcID3)
                            .addGap(18, 18, 18)
                            .addComponent(opcNombre3)
                            .addGap(18, 18, 18)
                            .addComponent(BoxBuscarUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(TBuscarUE, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(BuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(BuscarUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(BuscarLibro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(TBuscarPM, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opcID5)
                        .addGap(18, 18, 18)
                        .addComponent(opcNombre5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(opcFecha5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BoxBuscarUE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BVerEmpleados)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TBorrarL, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TBorrarUE, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TBorrarPM, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(opcID2)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(38, 38, 38)
                                                .addComponent(opcTitulo2)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(BVerLibros)
                                                    .addComponent(BAgregarL))
                                                .addGap(76, 76, 76))
                                            .addComponent(BVerUsuarios, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BVerPrestamos, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(opcID6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(opcNombre6)
                                        .addGap(16, 16, 16)
                                        .addComponent(opcFecha6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BoxBorrarUE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NomUsuario)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(opcID4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opcNombre4)
                                        .addGap(27, 27, 27)
                                        .addComponent(BoxBorrarUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BorrarUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BorraPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(BuscarLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BVerMultas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDatos)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BAgregarPM)
                            .addComponent(BSalir))))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(NomUsuario)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TBuscarL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TBorrarL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcTitulo1)
                            .addComponent(opcID1)
                            .addComponent(opcAutor)
                            .addComponent(opcEditorial)
                            .addComponent(opcTitulo2)
                            .addComponent(opcID2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BVerLibros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BAgregarL)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TBuscarUE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TBorrarUE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(BVerUsuarios)
                        .addGap(18, 18, 18)
                        .addComponent(BVerEmpleados)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcNombre3)
                    .addComponent(opcID3)
                    .addComponent(opcNombre4)
                    .addComponent(opcID4)
                    .addComponent(BoxBuscarUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxBorrarUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BuscarUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BorrarUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TBuscarPM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TBorrarPM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcNombre5)
                            .addComponent(opcID5)
                            .addComponent(opcNombre6)
                            .addComponent(opcID6)
                            .addComponent(BoxBuscarUE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxBorrarUE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcFecha5)
                            .addComponent(opcFecha6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarLibro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BorraPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(BVerPrestamos)
                        .addGap(18, 18, 18)
                        .addComponent(BVerMultas)
                        .addGap(18, 18, 18)
                        .addComponent(BAgregarPM)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSalir)
                    .addComponent(BDatos))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcTitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcTitulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcTitulo1ActionPerformed

    private void opcID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcID1ActionPerformed

    private void opcAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcAutorActionPerformed

    private void opcEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcEditorialActionPerformed

    private void BuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarLibroActionPerformed
        if(opcID1.isSelected()){

        }else if(opcTitulo1.isSelected()){

        }else if(opcAutor.isSelected()){

        }else if(opcEditorial.isSelected()){

        }
    }//GEN-LAST:event_BuscarLibroActionPerformed

    private void BVerLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BVerLibrosActionPerformed

    private void BDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDatosActionPerformed

    private void opcTitulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcTitulo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcTitulo2ActionPerformed

    private void opcID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcID2ActionPerformed

    private void BuscarLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarLibro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarLibro1ActionPerformed

    private void BAgregarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BAgregarLActionPerformed

    private void BorrarUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarUEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarUEActionPerformed

    private void BVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BVerUsuariosActionPerformed

    private void BuscarUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarUEActionPerformed

    private void opcNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcNombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcNombre3ActionPerformed

    private void opcID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcID3ActionPerformed

    private void opcNombre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcNombre4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcNombre4ActionPerformed

    private void opcID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcID4ActionPerformed

    private void BVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BVerEmpleadosActionPerformed

    private void BVerMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerMultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BVerMultasActionPerformed

    private void BorraPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorraPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorraPMActionPerformed

    private void BVerPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BVerPrestamosActionPerformed

    private void BuscarLibro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarLibro5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarLibro5ActionPerformed

    private void opcNombre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcNombre5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcNombre5ActionPerformed

    private void opcID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcID5ActionPerformed

    private void opcNombre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcNombre6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcNombre6ActionPerformed

    private void opcID6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcID6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcID6ActionPerformed

    private void BAgregarPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BAgregarPMActionPerformed

    private void opcFecha5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcFecha5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcFecha5ActionPerformed

    private void opcFecha6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcFecha6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcFecha6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregarL;
    private javax.swing.JButton BAgregarPM;
    private javax.swing.JButton BDatos;
    private javax.swing.JButton BSalir;
    private javax.swing.JButton BVerEmpleados;
    private javax.swing.JButton BVerLibros;
    private javax.swing.JButton BVerMultas;
    private javax.swing.JButton BVerPrestamos;
    private javax.swing.JButton BVerUsuarios;
    private java.awt.Button BorraPM;
    private java.awt.Button BorrarUE;
    private javax.swing.JComboBox<String> BoxBorrarUE;
    private javax.swing.JComboBox<String> BoxBorrarUE1;
    private javax.swing.JComboBox<String> BoxBuscarUE;
    private javax.swing.JComboBox<String> BoxBuscarUE1;
    private java.awt.Button BuscarLibro;
    private java.awt.Button BuscarLibro1;
    private java.awt.Button BuscarLibro5;
    private java.awt.Button BuscarUE;
    private javax.swing.JLabel NomUsuario;
    private javax.swing.JTextField TBorrarL;
    private javax.swing.JTextField TBorrarPM;
    private javax.swing.JTextField TBorrarUE;
    private javax.swing.JTextField TBuscarL;
    private javax.swing.JTextField TBuscarPM;
    private javax.swing.JTextField TBuscarUE;
    private javax.swing.ButtonGroup grupoOpciones;
    private javax.swing.ButtonGroup grupoOpciones2;
    private javax.swing.ButtonGroup grupoOpciones3;
    private javax.swing.ButtonGroup grupoOpciones4;
    private javax.swing.ButtonGroup grupoOpciones5;
    private javax.swing.ButtonGroup grupoOpciones6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JRadioButton opcAutor;
    private javax.swing.JRadioButton opcEditorial;
    private javax.swing.JRadioButton opcFecha5;
    private javax.swing.JRadioButton opcFecha6;
    private javax.swing.JRadioButton opcID1;
    private javax.swing.JRadioButton opcID2;
    private javax.swing.JRadioButton opcID3;
    private javax.swing.JRadioButton opcID4;
    private javax.swing.JRadioButton opcID5;
    private javax.swing.JRadioButton opcID6;
    private javax.swing.JRadioButton opcNombre3;
    private javax.swing.JRadioButton opcNombre4;
    private javax.swing.JRadioButton opcNombre5;
    private javax.swing.JRadioButton opcNombre6;
    private javax.swing.JRadioButton opcTitulo1;
    private javax.swing.JRadioButton opcTitulo2;
    // End of variables declaration//GEN-END:variables
}
