/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bibiloteca;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vanessa
 */
public class VEmpleado extends javax.swing.JFrame {

    private final Biblioteca MiBiblioteca;
    //private Empleado empleado;

    /**
     * Creates new form VUsuario
     * @throws java.io.IOException
     */
    private int idEmpleado;
    private String nombreEmpleado;
    public VEmpleado(int id) throws IOException {
        super("Biblioteca/Empleado");
        this.MiBiblioteca = Biblioteca.getInstance();
        initComponents();
        idEmpleado = id;
        nombreEmpleado = MiBiblioteca.BuscarEmpleado(idEmpleado).getNombre();
        String nombre = "Bienvenido  " + nombreEmpleado; //+ empleado.getNombre();
        Inicio.setText(nombre);
        
        //grupos de botones
        grupoOpciones.add(OpcID1);
        grupoOpciones.add(OpcTitulo1);
        grupoOpciones.add(OpcAutor1);
        grupoOpciones.add(OpcEditorial1);
        grupoOpciones2.add(OpcID2);
        grupoOpciones3.add(OpcID3);
        grupoOpciones3.add(OpcNombre3);
        grupoOpciones4.add(OpcID4);
        grupoOpciones5.add(OpcID5);
        grupoOpciones5.add(OpcNombre5);
        grupoOpciones5.add(OpcFecha5);
        grupoOpciones6.add(OpcID6);
        //si no eligue ninguna opcion para buscar o borrar
        Error1.setVisible(false); 
        Error2.setVisible(false); 
        Error3.setVisible(false); 
        Error4.setVisible(false); 
        Error5.setVisible(false); 
        Error6.setVisible(false); 
    }

    VEmpleado() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOpciones = new javax.swing.ButtonGroup();
        grupoOpciones2 = new javax.swing.ButtonGroup();
        grupoOpciones3 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        grupoOpciones4 = new javax.swing.ButtonGroup();
        grupoOpciones5 = new javax.swing.ButtonGroup();
        grupoOpciones6 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Inicio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BuscarL = new javax.swing.JTextField();
        Buscarpm = new javax.swing.JTextField();
        BuscarL2 = new javax.swing.JTextField();
        OpcEditorial1 = new javax.swing.JRadioButton();
        OpcID1 = new javax.swing.JRadioButton();
        OpcTitulo1 = new javax.swing.JRadioButton();
        OpcAutor1 = new javax.swing.JRadioButton();
        BBuscarMP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        BorrarL = new javax.swing.JTextField();
        OpcID2 = new javax.swing.JRadioButton();
        OpcID5 = new javax.swing.JRadioButton();
        OpcNombre5 = new javax.swing.JRadioButton();
        BBuscarL1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        BuscarL3 = new javax.swing.JTextField();
        OpcID4 = new javax.swing.JRadioButton();
        OpcID3 = new javax.swing.JRadioButton();
        OpcNombre3 = new javax.swing.JRadioButton();
        OpcFecha5 = new javax.swing.JRadioButton();
        BBuscarUE1 = new javax.swing.JButton();
        BoxUE1 = new javax.swing.JComboBox<>();
        BoxMP1 = new javax.swing.JComboBox<>();
        Error1 = new javax.swing.JLabel();
        Error3 = new javax.swing.JLabel();
        Error5 = new javax.swing.JLabel();
        BSalir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BALibro = new javax.swing.JButton();
        BLibros = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BoxMP2 = new javax.swing.JComboBox<>();
        OpcID6 = new javax.swing.JRadioButton();
        BorrarPM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BBuscarMP1 = new javax.swing.JButton();
        Error6 = new javax.swing.JLabel();
        BoxUE2 = new javax.swing.JComboBox<>();
        BBorrarUE = new javax.swing.JButton();
        Error4 = new javax.swing.JLabel();
        BBorrarL = new javax.swing.JButton();
        Error2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        Inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inicio.setText("jLabel1");
        getContentPane().add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 810, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setText("Usuarios y empleado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 190, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setText("Multas y préstamos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 170, 40));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setText("Libros");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 20));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel5.setText("Buscar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 70, 30));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel6.setText("Buscar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 30));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel7.setText("Buscar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 70, 30));

        BuscarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarLActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 210, 30));
        getContentPane().add(Buscarpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 160, 30));
        getContentPane().add(BuscarL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 30));

        OpcEditorial1.setBackground(new java.awt.Color(187, 143, 206));
        OpcEditorial1.setText("Editorial");
        OpcEditorial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcEditorial1ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcEditorial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 93, -1));

        OpcID1.setBackground(new java.awt.Color(187, 143, 206));
        OpcID1.setText("ID");
        OpcID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcID1ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 93, -1));

        OpcTitulo1.setBackground(new java.awt.Color(187, 143, 206));
        OpcTitulo1.setText("Titulo");
        OpcTitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcTitulo1ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 93, -1));

        OpcAutor1.setBackground(new java.awt.Color(187, 143, 206));
        OpcAutor1.setText("Autor");
        OpcAutor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcAutor1ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcAutor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 93, -1));

        BBuscarMP.setBackground(new java.awt.Color(74, 35, 90));
        BBuscarMP.setForeground(new java.awt.Color(255, 255, 255));
        BBuscarMP.setText("Buscar");
        BBuscarMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarMPActionPerformed(evt);
            }
        });
        getContentPane().add(BBuscarMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 73, -1));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel8.setText("Borrar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 70, 30));

        BorrarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarLActionPerformed(evt);
            }
        });
        getContentPane().add(BorrarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 160, 30));

        OpcID2.setBackground(new java.awt.Color(187, 143, 206));
        OpcID2.setText("ID");
        OpcID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcID2ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 93, -1));

        OpcID5.setBackground(new java.awt.Color(187, 143, 206));
        OpcID5.setText("ID de usurio");
        OpcID5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcID5ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 93, -1));

        OpcNombre5.setBackground(new java.awt.Color(187, 143, 206));
        OpcNombre5.setText("ID");
        OpcNombre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcNombre5ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 140, -1));

        BBuscarL1.setBackground(new java.awt.Color(74, 35, 90));
        BBuscarL1.setForeground(new java.awt.Color(255, 255, 255));
        BBuscarL1.setText("Buscar");
        BBuscarL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarL1ActionPerformed(evt);
            }
        });
        getContentPane().add(BBuscarL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 73, -1));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel9.setText("Borrar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 70, 30));

        BuscarL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarL3ActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 210, 30));

        OpcID4.setBackground(new java.awt.Color(187, 143, 206));
        OpcID4.setText("ID");
        OpcID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcID4ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 93, -1));

        OpcID3.setBackground(new java.awt.Color(187, 143, 206));
        OpcID3.setText("ID");
        OpcID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcID3ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 93, -1));

        OpcNombre3.setBackground(new java.awt.Color(187, 143, 206));
        OpcNombre3.setText("Nombre");
        OpcNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcNombre3ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 93, -1));

        OpcFecha5.setBackground(new java.awt.Color(187, 143, 206));
        OpcFecha5.setText("Fecha");
        OpcFecha5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcFecha5ActionPerformed(evt);
            }
        });
        getContentPane().add(OpcFecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 140, -1));

        BBuscarUE1.setBackground(new java.awt.Color(74, 35, 90));
        BBuscarUE1.setForeground(new java.awt.Color(255, 255, 255));
        BBuscarUE1.setText("Buscar");
        BBuscarUE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarUE1ActionPerformed(evt);
            }
        });
        getContentPane().add(BBuscarUE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 73, -1));

        BoxUE1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Empleado" }));
        getContentPane().add(BoxUE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 90, -1));

        BoxMP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Multa", "Prestamo" }));
        getContentPane().add(BoxMP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 90, -1));

        Error1.setForeground(new java.awt.Color(255, 0, 0));
        Error1.setText("Elija una opción");
        getContentPane().add(Error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 90, -1));

        Error3.setForeground(new java.awt.Color(255, 0, 0));
        Error3.setText("Elija una opción");
        getContentPane().add(Error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 90, -1));

        Error5.setForeground(new java.awt.Color(255, 0, 0));
        Error5.setText("Elija una opción");
        getContentPane().add(Error5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 90, -1));

        BSalir.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        BSalir.setText("Cerrar sesión");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 150, 23));

        jButton2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jButton2.setText("Mis datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 130, 23));

        BALibro.setText("Agregar nuevo libro");
        BALibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BALibroActionPerformed(evt);
            }
        });
        getContentPane().add(BALibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 200, -1));

        BLibros.setText("Mostrar Todos los libros");
        BLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLibrosActionPerformed(evt);
            }
        });
        getContentPane().add(BLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 200, -1));

        jButton4.setText("Mostrar Todos los usuarios");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 670, 190, -1));

        jButton5.setText("Agregar nuevo prestamo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, 170, -1));

        jButton6.setText("Mostrar Todos los empleado");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 190, -1));

        jButton7.setText("Agregar nueva multa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 670, 170, -1));

        jButton8.setText("Mostar todas los prestamos");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 190, -1));

        jButton9.setText("Mostar todas las multas");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 670, 190, -1));

        jPanel1.setBackground(new java.awt.Color(187, 143, 206));

        BoxMP2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Multa", "Prestamo" }));

        OpcID6.setBackground(new java.awt.Color(187, 143, 206));
        OpcID6.setText("ID");
        OpcID6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcID6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel10.setText("Borrar");

        BBuscarMP1.setBackground(new java.awt.Color(74, 35, 90));
        BBuscarMP1.setForeground(new java.awt.Color(255, 255, 255));
        BBuscarMP1.setText("Buscar");
        BBuscarMP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarMP1ActionPerformed(evt);
            }
        });

        Error6.setForeground(new java.awt.Color(255, 0, 0));
        Error6.setText("Elija una opción");

        BoxUE2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Empleado" }));

        BBorrarUE.setBackground(new java.awt.Color(74, 35, 90));
        BBorrarUE.setForeground(new java.awt.Color(255, 255, 255));
        BBorrarUE.setText("Borra");
        BBorrarUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarUEActionPerformed(evt);
            }
        });

        Error4.setForeground(new java.awt.Color(255, 0, 0));
        Error4.setText("Elija una opción");

        BBorrarL.setBackground(new java.awt.Color(74, 35, 90));
        BBorrarL.setForeground(new java.awt.Color(255, 255, 255));
        BBorrarL.setText("Borrar");
        BBorrarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarLActionPerformed(evt);
            }
        });

        Error2.setForeground(new java.awt.Color(255, 0, 0));
        Error2.setText("Elija una opción");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(BBorrarL, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Error2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 368, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BoxUE2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BBorrarUE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BorrarPM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BBuscarMP1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpcID6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxMP2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(Error6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Error4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(BorrarPM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpcID6)
                    .addComponent(BoxMP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxUE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BBuscarMP1)
                            .addComponent(Error6)
                            .addComponent(BBorrarUE))
                        .addGap(18, 18, 18)
                        .addComponent(Error4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BBorrarL)
                            .addComponent(Error2))
                        .addGap(228, 228, 228))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpcEditorial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcEditorial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcEditorial1ActionPerformed

    private void OpcID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcID1ActionPerformed

    private void OpcTitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcTitulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcTitulo1ActionPerformed

    private void OpcAutor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcAutor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcAutor1ActionPerformed

    private void OpcID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcID2ActionPerformed

    private void OpcID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcID5ActionPerformed

    private void OpcNombre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcNombre5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcNombre5ActionPerformed

    private void OpcID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcID4ActionPerformed

    private void OpcID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcID3ActionPerformed

    private void OpcNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcNombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcNombre3ActionPerformed

    private void OpcFecha5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcFecha5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcFecha5ActionPerformed

    private void OpcID6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcID6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcID6ActionPerformed

    private void BBuscarL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarL1ActionPerformed

        if(OpcID1.isSelected()){ //buscar libro por ID
            Error1.setVisible(false); 
            ArrayList<String> busqueda = new ArrayList();
            ArrayList<Libro> lib = new ArrayList();
            int id = Integer.parseInt(BuscarL2.getText());
            lib.add(MiBiblioteca.BuscarLibro(id));
            for(Libro l:lib){
                String dato = l.getDescripcion();
                busqueda.add(dato);
            }
            VBuscar MiBusqueda = new VBuscar(busqueda);
            MiBusqueda.setVisible(true);
            
        }else if(OpcTitulo1.isSelected()){ //buscar libro por titulo
            Error1.setVisible(false); 
            ArrayList<String> busqueda = new ArrayList();
            ArrayList<Libro> lib = new ArrayList();
            String titulo = BuscarL2.getText();
            lib = MiBiblioteca.BuscarLibro(titulo);
            for(Libro l:lib){
                String dato = l.getDescripcion();
                busqueda.add(dato);
            }
            VBuscar MiBusqueda = new VBuscar(busqueda);
            MiBusqueda.setVisible(true);

        }else if(OpcAutor1.isSelected()){ //buscar libro por autor
            Error1.setVisible(false); 
            ArrayList<String> busqueda = new ArrayList();
            ArrayList<Libro> lib = new ArrayList();
            String autor = BuscarL2.getText();
            lib = MiBiblioteca.BuscarAutor(autor);
            for(Libro l:lib){
                String dato = l.getDescripcion();
                busqueda.add(dato);
            }
            VBuscar MiBusqueda = new VBuscar(busqueda);
            MiBusqueda.setVisible(true);
            
        }else if(OpcEditorial1.isSelected()){ //buscar libro por editorial
            Error1.setVisible(false); 
            ArrayList<String> busqueda = new ArrayList();
            ArrayList<Libro> lib = new ArrayList();
            String editorial = BuscarL2.getText();
            lib = MiBiblioteca.BuscarEditorial(editorial);
            for(Libro l:lib){
                String dato = l.getDescripcion();
                busqueda.add(dato);
            }
            VBuscar MiBusqueda = new VBuscar(busqueda);
            MiBusqueda.setVisible(true);
        }else{ //si no elige nada
            Error1.setVisible(true);
        }
    }//GEN-LAST:event_BBuscarL1ActionPerformed

    private void BBorrarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarLActionPerformed
        if(OpcID2.isSelected()){ //borra libro por ID
            Error2.setVisible(false); 
                    int id = Integer.parseInt(BorrarL.getText());
                    VBorrar Borrar = new VBorrar();
                    Borrar.setVisible(true);
                    if(Borrar.setBandera()==true){
                        MiBiblioteca.BorrarLibro(id);
                    }

        }else{ //si no elige nada
            Error2.setVisible(true); 
        }
    }//GEN-LAST:event_BBorrarLActionPerformed

    private void BBuscarUE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarUE1ActionPerformed
        int opcion = BoxUE1.getSelectedIndex();
        if(opcion==0){ //usuario
            
            if(OpcID3.isSelected()){ //buscar por id
                Error3.setVisible(false); 
                ArrayList<String> busqueda = new ArrayList();
                ArrayList<Usuario> u = new ArrayList();
                    int id = Integer.parseInt(BuscarL.getText());
                    u.add(MiBiblioteca.BuscarUsuario(id));
                    for(Usuario us: u){
                        String dato = us.getDescripcion();
                        busqueda.add(dato);
                    }
                    VBuscar MiBusqueda = new VBuscar(busqueda);
                    MiBusqueda.setVisible(true);

            }else if(OpcNombre3.isSelected()){ //buscar por nombre
                Error3.setVisible(false); 
                ArrayList<String> busqueda = new ArrayList();
                ArrayList<Usuario> u = new ArrayList();
                    String nombre = BuscarL.getText();
                    u = MiBiblioteca.BuscarUsuario(nombre);
                    for(Usuario l:u){
                        String dato = l.getDescripcion();
                        busqueda.add(dato);
                    }
                    VBuscar MiBusqueda = new VBuscar(busqueda);
                    MiBusqueda.setVisible(true);
            }else{ //si no elige nada
                Error3.setVisible(true); 
            } 
        }
        else if(opcion==1){ //empleado
            if(OpcID3.isSelected()){ //buscar por id
                Error3.setVisible(false); 
                ArrayList<String> busqueda = new ArrayList();
                ArrayList<Empleado> e = new ArrayList();
                    int id = Integer.parseInt(BuscarL.getText());
                    e.add(MiBiblioteca.BuscarEmpleado(id));
                    for(Empleado em: e){
                        String dato = em.getDescripcion();
                        busqueda.add(dato);
                    }
                    VBuscar MiBusqueda = new VBuscar(busqueda);
                    MiBusqueda.setVisible(true);

            }else if(OpcNombre3.isSelected()){ //buscar por nombre
                Error3.setVisible(false);  
                ArrayList<String> busqueda = new ArrayList();
                ArrayList<Empleado> e = new ArrayList();
                    String nombre = BuscarL.getText();
                    e = MiBiblioteca.BuscarEmpleado(nombre);
                    for(Empleado em: e){
                        String dato = em.getDescripcion();
                        busqueda.add(dato);
                    }
                    VBuscar MiBusqueda = new VBuscar(busqueda);
                    MiBusqueda.setVisible(true);
            }else{ //si no elige nada
                Error3.setVisible(true); 
            } 
        }
    }//GEN-LAST:event_BBuscarUE1ActionPerformed

    private void BBorrarUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarUEActionPerformed
        int opcion = BoxUE2.getSelectedIndex();
        if(opcion==0){ //usuario
            if(OpcID4.isSelected()){ //borrar por id
                Error4.setVisible(false); 
                    int id = Integer.parseInt(BuscarL3.getText());
                    VBorrar Borrar = new VBorrar();
                    Borrar.setVisible(true);
                    //if(Borrar.setBandera()==true){
                        MiBiblioteca.eliminarEnArchivo("ArchivoUsuarios", id);
                    //}
            }else{ //si no elige nada
                Error4.setVisible(true); 
            } 
        }
        else if(opcion==1){ //empleado
            if(OpcID4.isSelected()){ //borrar por id
                Error4.setVisible(false); 
                    int id = Integer.parseInt(BuscarL3.getText());
                    VBorrar Borrar = new VBorrar();
                    Borrar.setVisible(true);
                    if(Borrar.setBandera()==true){
                        MiBiblioteca.BorrarEmpleado(id);
                    }
            
            }else{ //si no elige nada
                Error4.setVisible(true); 
            }
        }
    }//GEN-LAST:event_BBorrarUEActionPerformed

    private void BBuscarMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarMPActionPerformed
        int opcion = BoxMP1.getSelectedIndex();
        if(opcion==0){ //multa
            if(OpcID5.isSelected()){ //buscar por id
                ArrayList<String> busqueda = new ArrayList();
                ArrayList<Multa> m = new ArrayList();
                Error5.setVisible(false); 
                    int id = Integer.parseInt(Buscarpm.getText());
                    m = MiBiblioteca.BuscarMultasUsuario(id);
                    for(Multa mu: m){
                        String dato = mu.getDescripcion();
                        busqueda.add(dato);
                    }
                    VBuscar MiBusqueda = new VBuscar(busqueda);
                    MiBusqueda.setVisible(true);

            }else if(OpcNombre5.isSelected()){ //buscar por nombre
                ArrayList<String> busqueda = new ArrayList();
                ArrayList<Multa> m = new ArrayList();
                Error5.setVisible(false); 
                    int id = Integer.parseInt(Buscarpm.getText());
                    m.add(MiBiblioteca.BuscarMulta(id));
                    for(Multa mu: m){
                        String dato = mu.getDescripcion();
                        busqueda.add(dato);
                    }
                    VBuscar MiBusqueda = new VBuscar(busqueda);
                    MiBusqueda.setVisible(true);
            }else if(OpcFecha5.isSelected()){ //buscar por fecha
                Error5.setVisible(false); 
                ArrayList<String> busqueda = new ArrayList();
                ArrayList<Multa> m = new ArrayList();
                    String fecha = Buscarpm.getText();
                    m = MiBiblioteca.BuscarMultasFecha(fecha);
                    for(Multa mu: m){
                        String dato = mu.getDescripcion();
                        busqueda.add(dato);
                    }
                    VBuscar MiBusqueda = new VBuscar(busqueda);
                    MiBusqueda.setVisible(true);

            }else{ //si no elige nada
                Error5.setVisible(true); 
            } 
        }
        else if(opcion==1){ //prestamo
            if(OpcID5.isSelected()){ //buscar por id
                ArrayList<String> busqueda = new ArrayList();
                ArrayList<Prestamo> p = new ArrayList();
                Error5.setVisible(false); 
                int id = Integer.parseInt(Buscarpm.getText());
                    p = MiBiblioteca.BuscarPrestamosUsuario(id);
                    for(Prestamo pre:p){
                        String dato = pre.getDescripcion();
                        busqueda.add(dato);
                    }
                    VBuscar MiBusqueda = new VBuscar(busqueda);
                    MiBusqueda.setVisible(true);

            }else if(OpcNombre5.isSelected()){ //buscar por nombre
                ArrayList<String> busqueda = new ArrayList();
                ArrayList<Prestamo> p = new ArrayList();
                Error5.setVisible(false); 
                    int id = Integer.parseInt(Buscarpm.getText());
                    p.add(MiBiblioteca.BuscarPrestamo(id));
                    for(Prestamo pre:p){
                        String dato = pre.getDescripcion();
                        busqueda.add(dato);
                    }
                    VBuscar MiBusqueda = new VBuscar(busqueda);
                    MiBusqueda.setVisible(true);

            }else if(OpcFecha5.isSelected()){ //buscar por fecha
                Error5.setVisible(false); 
                ArrayList<String> busqueda = new ArrayList();
                ArrayList<Prestamo> p = new ArrayList();
                    String fecha = Buscarpm.getText();
                    p = MiBiblioteca.BuscarPrestamosFecha(fecha);
                    for(Prestamo pre:p){
                        String dato = pre.getDescripcion();
                        busqueda.add(dato);
                    }
                    VBuscar MiBusqueda = new VBuscar(busqueda);
                    MiBusqueda.setVisible(true);

            }else{ //si no elige nada
                Error5.setVisible(true); 
            }
        }
    }//GEN-LAST:event_BBuscarMPActionPerformed

    private void BBuscarMP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarMP1ActionPerformed
        int opcion = BoxMP1.getSelectedIndex();
        if(opcion==0){ //multa
            if(OpcID6.isSelected()){ //borrar por id
                Error6.setVisible(false); 
                    int id = Integer.parseInt(BorrarPM.getText());
                    VBorrar Borrar = new VBorrar();
                    Borrar.setVisible(true);
                    if(Borrar.setBandera()==true){
                        MiBiblioteca.BorrarMulta(id);
                    }

            }else{ //si no elige nada
                Error6.setVisible(true); 
            } 
        }
        else if(opcion==1){ //prestamo
            if(OpcID6.isSelected()){ //borrar por id
                Error6.setVisible(false); 
                    int id = Integer.parseInt(BorrarPM.getText());
                    VBorrar Borrar = new VBorrar();
                    Borrar.setVisible(true);
                    if(Borrar.setBandera()==true){
                        MiBiblioteca.BorrarPrestamo(id);
                    }

            }else{ //si no elige nada
                Error6.setVisible(true); 
            }
        }
    }//GEN-LAST:event_BBuscarMP1ActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed

        if(evt.getSource()==BSalir){           
            VentanaPrincipal regresar = new VentanaPrincipal();
            regresar.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_BSalirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Empleado e = new Empleado();
        ArrayList<String> datos = new ArrayList();
        e = MiBiblioteca.BuscarEmpleado(idEmpleado);
            String dato = e.getDescripcion();
            datos.add(dato);
        VBuscar MiBusqueda = new VBuscar(datos);
        MiBusqueda.setVisible(true); 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ArrayList<Usuario> us = new ArrayList();
        ArrayList<String> datos = new ArrayList();
        us = MiBiblioteca.getUsuarios();
        for(Usuario u:us){
            String dato = u.getDescripcion();
            datos.add(dato);
        }
        VBuscar MiBusqueda = new VBuscar(datos);
            MiBusqueda.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLibrosActionPerformed
        ArrayList<Libro> lib = new ArrayList();
        ArrayList<String> datos = new ArrayList();
        lib = MiBiblioteca.getLibros();
        for(Libro l:lib){
            String dato = l.getDescripcion();
            datos.add(dato);
        }
        VBuscar MiBusqueda = new VBuscar(datos);
            MiBusqueda.setVisible(true);
    }//GEN-LAST:event_BLibrosActionPerformed

    private void BALibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BALibroActionPerformed
        try {
            VAgregarL libronew = new VAgregarL();
            libronew.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(VEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BALibroActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        VAgregarPM pre;
        try {
            pre = new VAgregarPM();
            pre.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(VUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        VAgregarPM pre;
        try {
            pre = new VAgregarPM();
            pre.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(VUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ArrayList<Empleado> emp = new ArrayList();
        ArrayList<String> datos = new ArrayList();
        emp = MiBiblioteca.getEmpleado();
        for(Empleado e: emp){
            String dato = e.getDescripcion();
            datos.add(dato);
        }
        VBuscar MiBusqueda = new VBuscar(datos);
            MiBusqueda.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        ArrayList<Documentos> doc = new ArrayList();
        ArrayList<String> datos = new ArrayList();
        doc = MiBiblioteca.getDocumentos();
        for(Documentos d:doc){
            if(d instanceof Prestamo){
                String dato = d.getDescripcion();
                datos.add(dato);
            }
        }
        VBuscar MiBusqueda = new VBuscar(datos);
            MiBusqueda.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ArrayList<Documentos> doc = new ArrayList();
        ArrayList<String> datos = new ArrayList();
        doc = MiBiblioteca.getDocumentos();
        for(Documentos d:doc){
            if(d instanceof Multa){
                String dato = d.getDescripcion();
                datos.add(dato);
            }
        }
        VBuscar MiBusqueda = new VBuscar(datos);
            MiBusqueda.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void BuscarL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarL3ActionPerformed
 
    }//GEN-LAST:event_BuscarL3ActionPerformed

    private void BuscarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarLActionPerformed

    private void BorrarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BALibro;
    private javax.swing.JButton BBorrarL;
    private javax.swing.JButton BBorrarUE;
    private javax.swing.JButton BBuscarL1;
    private javax.swing.JButton BBuscarMP;
    private javax.swing.JButton BBuscarMP1;
    private javax.swing.JButton BBuscarUE1;
    private javax.swing.JButton BLibros;
    private javax.swing.JButton BSalir;
    private javax.swing.JTextField BorrarL;
    private javax.swing.JTextField BorrarPM;
    private javax.swing.JComboBox<String> BoxMP1;
    private javax.swing.JComboBox<String> BoxMP2;
    private javax.swing.JComboBox<String> BoxUE1;
    private javax.swing.JComboBox<String> BoxUE2;
    private javax.swing.JTextField BuscarL;
    private javax.swing.JTextField BuscarL2;
    private javax.swing.JTextField BuscarL3;
    private javax.swing.JTextField Buscarpm;
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel Error2;
    private javax.swing.JLabel Error3;
    private javax.swing.JLabel Error4;
    private javax.swing.JLabel Error5;
    private javax.swing.JLabel Error6;
    private javax.swing.JLabel Inicio;
    private javax.swing.JRadioButton OpcAutor1;
    private javax.swing.JRadioButton OpcEditorial1;
    private javax.swing.JRadioButton OpcFecha5;
    private javax.swing.JRadioButton OpcID1;
    private javax.swing.JRadioButton OpcID2;
    private javax.swing.JRadioButton OpcID3;
    private javax.swing.JRadioButton OpcID4;
    private javax.swing.JRadioButton OpcID5;
    private javax.swing.JRadioButton OpcID6;
    private javax.swing.JRadioButton OpcNombre3;
    private javax.swing.JRadioButton OpcNombre5;
    private javax.swing.JRadioButton OpcTitulo1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup grupoOpciones;
    private javax.swing.ButtonGroup grupoOpciones2;
    private javax.swing.ButtonGroup grupoOpciones3;
    private javax.swing.ButtonGroup grupoOpciones4;
    private javax.swing.ButtonGroup grupoOpciones5;
    private javax.swing.ButtonGroup grupoOpciones6;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
