/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bibiloteca;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vanessa
 */
public class VIniciar extends javax.swing.JFrame {

    private final Biblioteca MiBiblioteca;

    /**
     * Creates new form Iniciar
     */
    public VIniciar() throws IOException {
        super("Iniciar sesion");
        initComponents();
        Button.setVisible(false);
        this.MiBiblioteca = Biblioteca.getInstance();
        incorrecto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextFID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        Button = new javax.swing.JButton();
        TextFCon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        incorrecto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 52, -1, -1));

        TextFID.setBackground(new java.awt.Color(255, 240, 201));
        getContentPane().add(TextFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 51, 150, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 107, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jLabel4.setText("Tipo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 144, -1, -1));

        ComboBox.setBackground(new java.awt.Color(232, 195, 158));
        ComboBox.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Usuario", "Empleado" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 144, 150, -1));

        Button.setBackground(new java.awt.Color(210, 180, 140));
        Button.setText("Iniciar");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 204, -1, -1));

        TextFCon.setBackground(new java.awt.Color(255, 240, 201));
        getContentPane().add(TextFCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 106, 150, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Iniciar sesión");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 11, -1, -1));

        jPanel1.setBackground(new java.awt.Color(139, 99, 50));

        incorrecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        incorrecto.setForeground(new java.awt.Color(255, 0, 0));
        incorrecto.setText("Incorrecto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(incorrecto)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(incorrecto)
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        int opcion = ComboBox.getSelectedIndex();
        if(opcion ==1){ //usuario
            boolean bandera = false;
            int id = Integer.parseInt(TextFID.getText());
            String con = TextFCon.getText();
            Usuario usuario = MiBiblioteca.BuscarUsuario(id);
            if(usuario!=null){
                incorrecto.setText(usuario.getContrasenia());
                    incorrecto.setVisible(true);
                if(usuario.getContrasenia().equals(con)){
                    bandera =true;
                }
                    
            }
            if(bandera==true){  
                incorrecto.setVisible(false);
                VUsuario u;
                try {
                    u = new VUsuario(id); //se manda a Usuario, el usuario que inició
                    u.setVisible(true);
                    dispose();
                } catch (IOException ex) {
                    Logger.getLogger(VRegistrarse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                incorrecto.setVisible(true);
            }
            
        }else if(opcion == 2){ //empleado
             boolean bandera = false;
            int id = Integer.parseInt(TextFID.getText());
            String con = TextFCon.getText();
            Empleado em = new Empleado();
            em = MiBiblioteca.BuscarEmpleado(id);
            if(em!=null){
                if(em.getContrasenia().equals(con)){
                    bandera =true;
                }
                    
            }
            if(bandera==true){  
                incorrecto.setVisible(false);
                VEmpleado e;
                try {
                    e = new VEmpleado(id); //se manda a Empleado, el empleado que inició
                    e.setVisible(true);
                    dispose();
                } catch (IOException ex) {
                    Logger.getLogger(VRegistrarse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                incorrecto.setVisible(true);
            }
        }
    }//GEN-LAST:event_ButtonActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
       Button.setVisible(true);
    }//GEN-LAST:event_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VIniciar().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VIniciar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTextField TextFCon;
    private javax.swing.JTextField TextFID;
    private javax.swing.JLabel incorrecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
