/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pf;

/**
 *
 * @author Vanessa
 */
public class VUsuario extends javax.swing.JFrame {
    //private Usuario usuario;

    /**
     * Creates new form VUsuario
     */
    public VUsuario() {
        super("Biblioteca/Usuario");
        //usuario = usu;
        initComponents();
        grupoOpciones.add(opcID);
        grupoOpciones.add(opcTitulo);
        grupoOpciones.add(opcAutor);
        grupoOpciones.add(opcEditorial);
        String nombre = "Bienvenido  " + "Vanessa"; //´+ usuario.getNombre();
        NomUsuario.setText(nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOpciones = new javax.swing.ButtonGroup();
        BuscarLibro = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ButtonPedir = new javax.swing.JButton();
        opcTitulo = new javax.swing.JRadioButton();
        opcID = new javax.swing.JRadioButton();
        opcAutor = new javax.swing.JRadioButton();
        opcEditorial = new javax.swing.JRadioButton();
        NomUsuario = new javax.swing.JLabel();
        ButtonLibros = new javax.swing.JButton();
        ButtonDatos = new javax.swing.JButton();
        ButtonPrestamos = new javax.swing.JButton();
        ButtonMultas = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BuscarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BuscarLibro.setLabel("Buscar");
        BuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarLibroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setText("Buscar Libro");

        ButtonPedir.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        ButtonPedir.setText("Pedir Prestamo");
        ButtonPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPedirActionPerformed(evt);
            }
        });

        opcTitulo.setText("Titulo");
        opcTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcTituloActionPerformed(evt);
            }
        });

        opcID.setText("ID");
        opcID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcIDActionPerformed(evt);
            }
        });

        opcAutor.setText("Autor");
        opcAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAutorActionPerformed(evt);
            }
        });

        opcEditorial.setText("Editorial");
        opcEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcEditorialActionPerformed(evt);
            }
        });

        NomUsuario.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        NomUsuario.setText("jLabel4");

        ButtonLibros.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        ButtonLibros.setText("Todos los libros");
        ButtonLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLibrosActionPerformed(evt);
            }
        });

        ButtonDatos.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        ButtonDatos.setText("Mis datos");
        ButtonDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDatosActionPerformed(evt);
            }
        });

        ButtonPrestamos.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        ButtonPrestamos.setText("Mis prestamos");
        ButtonPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPrestamosActionPerformed(evt);
            }
        });

        ButtonMultas.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        ButtonMultas.setText("Mis multas");
        ButtonMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultasActionPerformed(evt);
            }
        });

        ButtonSalir.setText("Cerrar Sesión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonLibros, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ButtonPrestamos, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(15, 15, 15)
                                                            .addComponent(ButtonDatos))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(19, 19, 19)
                                                            .addComponent(ButtonMultas)))
                                                    .addGap(8, 8, 8)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(ButtonPedir)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(opcID)
                                    .addGap(18, 18, 18)
                                    .addComponent(opcTitulo)
                                    .addGap(18, 18, 18)
                                    .addComponent(opcAutor)
                                    .addGap(18, 18, 18)
                                    .addComponent(opcEditorial)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(BuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSalir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(NomUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(NomUsuario)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcTitulo)
                    .addComponent(opcID)
                    .addComponent(opcAutor)
                    .addComponent(opcEditorial))
                .addGap(37, 37, 37)
                .addComponent(ButtonLibros)
                .addGap(18, 18, 18)
                .addComponent(ButtonDatos)
                .addGap(18, 18, 18)
                .addComponent(ButtonPrestamos)
                .addGap(18, 18, 18)
                .addComponent(ButtonMultas)
                .addGap(18, 18, 18)
                .addComponent(ButtonPedir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(ButtonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPedirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPedirActionPerformed

    private void opcTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcTituloActionPerformed

    private void opcIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcIDActionPerformed

    private void opcAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcAutorActionPerformed

    private void opcEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcEditorialActionPerformed

    private void BuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarLibroActionPerformed
        if(opcID.isSelected()){

        }else if(opcTitulo.isSelected()){

        }else if(opcAutor.isSelected()){

        }else if(opcEditorial.isSelected()){

        }
    }//GEN-LAST:event_BuscarLibroActionPerformed

    private void ButtonLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonLibrosActionPerformed

    private void ButtonDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDatosActionPerformed

    private void ButtonPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPrestamosActionPerformed

    private void ButtonMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BuscarLibro;
    private javax.swing.JButton ButtonDatos;
    private javax.swing.JButton ButtonLibros;
    private javax.swing.JButton ButtonMultas;
    private javax.swing.JButton ButtonPedir;
    private javax.swing.JButton ButtonPrestamos;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel NomUsuario;
    private javax.swing.ButtonGroup grupoOpciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton opcAutor;
    private javax.swing.JRadioButton opcEditorial;
    private javax.swing.JRadioButton opcID;
    private javax.swing.JRadioButton opcTitulo;
    // End of variables declaration//GEN-END:variables
}
